@isTest 
public class CreateChildrenCaseHandler_tst{
    
    /*@isTest 
    static void CreateChildrenCase(){
        
        Product2 lProduct = Product2Factory.createProduct2Service();
        Insert lProduct;
        Case lCase = CaseFactory.createCasePortfolioAnalysis(lProduct);
        insert lCase;
            
        lCase.Status = 'Análise Operacional';
        lCase.Ability__c = 'Novo(a)';
        lCase.Parts__c = 'Novo(a)';
        lCase.Problem__c = 'Novo(a)';
        lCase.Modal__c = 'Novo(a)';
        lCase.OperationalService__c = 'Novo(a)';
        update lCase;
    }*/
}